package com.givinghands.givinghands.notification;

public enum EmailTemplateName {
    CAMPAIGN_APPROVED_ACTIVE,
    CAMPAIGN_GOAL_REACHED,
    NEW_VOLUNTEER_OPPORTUNITY,

    ORG_CAMPAIGN_APPROVED,
    ORG_CAMPAIGN_REJECTED,
    ORG_REGISTRATION_WELCOME,
    ORG_WELCOME_APPROVED,

    ORG_VOLUNTEER_APPLIED,

    USER_DONATION_SUBMITTED,
    USER_VOLUNTEER_APPROVED,
    USER_VOLUNTEER_REJECTED,

    ADMIN_CAMPAIGN_GOAL_REACHED,
    ADMIN_NEW_CAMPAIGN_REQUEST,
    ADMIN_NEW_ORG_REGISTERED
}

